### PR TITLE
Modified OstirConstants and a Python version of calibration script

### PR DESCRIPTION
**Pull request by yiduo-wang-32**
Hey Barrick Lab, 

This is Yiduo, a Rice Bioengineering graduate student co-advised by Dr. Caleb Bashor and Dr. Oleg Igoshin. Recently we have been working on a project that requires modifying the RBS calculator. Many headaches later I found your repo, which is well-written, well-maintained, and such a blessing to have. I just want to express my gratitude towards your lab, especially your dedication of making open-sourced toolkits and contributing to the whole community.

Anyway, since we are working with your code I think I can drop my contributions here that you might find useful, including a python version of calibration script, and some I/O features to the `OstirConstant` object. Please see the commit message and source code for the full log.

Thanks,
Yiduo

### CODE REVIEW

**Comment by jeffreybarrick** [comment]
Hi Yidou,

Thanks so much for contributing your improvements!

@croots plans to incorporate them when he has a chance.

**Comment by yiduo-wang-32** [comment]
Sounds good, thank you so much for this amazing package!

**Comment by croots** [comment]
Hi Yiduo! Thanks for your PR, these are excellent contributions. I've removed the output files from your python version of the calibration script just for housekeeping since they're automatically generated and they are redundant with the R generated files. I can see this being very useful for anybody more comfortable in python than in R. and the cleaned up string method is nice as well.

Reviewed and merged. Thanks for your patience as I've been in crunch on some other tasks.

**Comment by yiduo-wang-32** [comment]
Thank you, it's a pleasure to contribute to this package and community!

**Pull request merged**
